config/routes.rb
Ideagora::Application.routes.draw do

  get "welcome/index"
  get "sign_in" => "sessions#new", :as => "sign_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "my_profile" => "users#edit", :as => "my_profile"
  get "projects" => "projects#index", :as => "projects"
  
  resources :camps
  resources :notices
  resources :sessions
  resources :talks
  resources :venues
  resources :users, :only => [:index, :show, :edit, :update] do
    resources :projects
  end

  root :to => "welcome#index"

end

app/models/talk.rb
class Talk < ActiveRecord::Base
  belongs_to :user
  belongs_to :venue
  belongs_to :camp #denormalized from venue because talks start off w/out a venue when a camp is created

  validates_presence_of :user_id
  validates_presence_of :venue_id
  validates_presence_of :start_at
  validates_presence_of :end_at
  validate :start_at_is_less_than_end_at

  def self.for_day(day)
    where('start_at >= ? and start_at < ?', day, day + 1.day).order(:start_at)
  end

  def day
    start_at.to_date
  end

  private

  def start_at_is_less_than_end_at
    if start_at.blank? || end_at.blank? || start_at >= end_at
      errors.add :start_at, "The start time must be before the end time" 
    end
  end
end

app/controllers/talks_controller.rb
class TalksController < InheritedResources::Base
  before_filter :requires_login

  def index
    @day = params[:day] ? Date.parse(params[:day]) : Camp.current.talks.order(:start_at).first.day
    @venues = Camp.current.venues
    @days_with_talks = Camp.current.talks.collect(&:day).uniq.sort
    @talks_by_time_and_venue_for_day = Camp.current.talks_by_time_and_venue_for_day(@day)
    index!
  end

  def new
    @users = Camp.current.users.order(:first_name)
    @start_at = Time.parse(params[:start_at])
    @end_at = @start_at + 1.hour
    @venue = Venue.find(params[:venue_id])
    @talk = Talk.new(:start_at => @start_at, :end_at => @end_at, :venue => @venue, :user => current_user)
    new!
  end

  def edit
    @users = Camp.current.users.order(:first_name)
    edit!
  end

  def create
    @talk = Talk.new(params[:talk])
    @talk.user = current_user
    create!
  end
end

app/helpers/talks_helper.rb
module TalksHelper
  def casual_day_description(time)
    time = time.to_time if time.class == Date
    time_diff = time - Time.now
    if time_diff < 0 
      case time_diff.abs
        when 0..1.day then 'Yesterday'
        else "#{time.strftime("%A, %d %B, %Y")}"
      end
    else
      case time_diff
        when 0...1.day then 'Today'
        when 1.day...2.days then 'Tomorrow'
        when 2.days...7.days then "This #{time.strftime("%A")}"
        else "#{time.strftime("%A, %d %B, %Y")}"
      end
    end
  end

  def talk_description(talk)
    html = <<-END
      #{talk.try(:name)} <br/>
      #{talk.try(:user).try(:full_name)}
    END
    html.html_safe
  end
end

app/views/talks/_form.html.haml
= render :partial => 'where_and_when', :locals => { :talk => @talk }

= simple_form_for @talk do |f|
  = f.input :name, :label => 'Talk Title'
  = f.input :user_id, :label => 'Speaker',  :collection => @users, :label_method => :full_name, :value_method => :id
  = f.button :submit

  = f.input :start_at, :as => :hidden
  = f.input :end_at, :as => :hidden
  = f.input :venue_id, :as => :hidden

app/views/talks/_where_and_when.html.haml
%p
  == Venue: #{talk.venue.name}
%p
  == #{casual_day_description(talk.start_at.to_date)} from #{talk.start_at.strftime("%H:%M")} to #{talk.end_at.strftime("%H:%M")}

app/views/talks/edit.html.haml
%h2 Edit Talk

= render 'form'

app/views/talks/index.html.haml
%h2== Talks for #{casual_day_description(@day)}
%h3 Change Day
- @days_with_talks.each do |day|
  = day == @day ? day.strftime("%A") : link_to(day.strftime("%A"), talks_path(:day => day))
%table.talks
  %thead
    %tr
      %th Time
      -  @venues.each do |venue|
        %th= venue.name
  %tbody
    - Camp.current.talk_hours.each_with_index do |hour, index|
      - time = @day + hour.hours
      %tr{:class => index.even? ? 'even' : 'odd'}
        %td
          = time.strftime "%H:%M"
          - @venues.each do |venue|
            - talk = @talks_by_time_and_venue_for_day[time] && @talks_by_time_and_venue_for_day[time][venue]
            %td{:class => talk ? 'filled' : 'available'}
              - if talk
                = link_to talk_description(talk), talk_path(talk)
              - else
                = link_to "Add Talk", new_talk_path(:start_at => time, :venue_id => venue.id)

app/views/talks/new.html.haml
%h2 New Talk

= render 'form'

app/views/talks/show.html.haml
%h2.name= @talk.name
%h3.speaker= @talk.user.full_name

%p
  == Venue: #{@talk.venue.name}
%p
  == #{casual_day_description(@talk.start_at.to_date)} from #{@talk.start_at.strftime("%H:%M")} to #{@talk.end_at.strftime("%H:%M")}

=link_to "Edit this talk", edit_talk_path(@talk)
=link_to "Delete this talk", talk_path(@talk), :method => :delete, :confirm => 'Really delete this talk?'