config/routes.rb
Ideagora::Application.routes.draw do

  get "welcome/index"
  get "sign_in" => "sessions#new", :as => "sign_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "my_profile" => "users#edit", :as => "my_profile"
  get "projects" => "projects#index", :as => "projects"
  
  resources :camps
  resources :notices
  resources :sessions
  resources :talks
  resources :venues
  resources :users, :only => [:index, :show, :edit, :update] do
    resources :projects
  end

  root :to => "welcome#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :attendances
  has_many :camps, :through => :attendances
  has_many :projects, :dependent => :destroy
  has_many :notices
  
  validates_presence_of :first_name, :email
  validates_uniqueness_of :email
  
  scope :organisers, :joins => :attendances, :conditions => ["attendances.organiser = ? and attendances.camp_id = ?", true, Camp.current] 
  
  acts_as_taggable
  acts_as_taggable_on :skills, :interests
  
  def full_name
    if last_name
      first_name + ' ' + last_name
    else
      first_name
    end
  end
  
  def organiser?
    User.organisers.include?(self)
  end
  
  def self.authenticate(param)
    user = find_by_email(param) || find_by_twitter(param)
    user ? user : nil
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  actions :index, :show, :update
  before_filter :requires_login, :except => [:index, :show]

  def edit
    @user = current_user
    @skills_tags_json = User.tag_counts_on(:skills).to_json
    @interests_tags_json = User.tag_counts_on(:interests).to_json
  end

  def update
    update! { my_profile_path }
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def get_gravatar(user, size) #you can request an image size between 1px - 512px.
    email_md5 = Digest::MD5.hexdigest(user.email).to_s
    url = "http://www.gravatar.com/avatar/" + email_md5 + "?s=" + size.to_s
  end
end

app/views/users/edit.html.haml
%h2 Edit my details

- content_for :header do
  :javascript
    window.skills_tags_objs = #{@skills_tags_json};
    window.interests_tags_objs = #{@interests_tags_json};
  
  = javascript_include_tag 'users/edit'



= simple_form_for @user, :url => user_path(@user) do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :email
  = f.input :bio, :hint => 'Textile supported'
  = f.input :twitter
  = f.input :bonjour
  = f.input :irc
  = f.input :skill_list, :input_html => { :value => @user.skill_list.sort }
  = f.input :interest_list, :input_html => { :value => @user.interest_list.sort }

  %p.submits
    = link_to 'Cancel', @user, :class => 'cancel'
    or
    = f.button :submit, :value => 'Save changes'

app/views/users/index.html.haml
- content_for :header do
  = javascript_include_tag 'vendor/jquery.dataTables-1.7.6.min'
  :javascript
    $(function(){
      $('table.users').dataTable({
        bJQueryUI: true,
        bPaginate: false,
        bLengthChange: false,
        bFilter: true,
        bSort: false,
        bAutoWidth: false
      });
    });

%h1 All The Campers

%table.users
  %thead
    %tr
      %th
      %th Name
      %th Bonjour
      %th Twitter
      %th IRC
      %th Bio
      %th Skills
      %th Interests
      %th 
  %tbody
    - @users.each_with_index do |user, index|
      - row_class = index.even? ? 'even' : 'odd'
      %tr{:class => row_class}
        %td
          %img.profile_pic{:src => get_gravatar(user, 80)}
        %td= user.full_name
        %td= user.bonjour
        %td= user.twitter
        %td= user.irc
        %td= user.bio
        %td= user.skill_list.join(', ')
        %td= user.interest_list.join(', ')
        %td= link_to('View', user_path(user))

app/views/users/show.html.haml
%h1= @user.full_name
  
%img.profile_pic{:src => get_gravatar(@user, 200)}

%p= link_to("edit my profile", edit_user_path(@user)) if current_user == @user

%p Email: #{@user.email}


%p Twitter username: #{@user.twitter}

%p Bonjour nick: #{@user.bonjour}

%p IRC nick: #{@user.irc}

%p= @user.try(:bio)

%p Skills: #{@user.skill_list.join(', ')}

%p Interests: #{@user.interest_list.join(', ')}

- if @user.projects.any?
  %h2 My projects
  %ol
    - for project in @user.projects
      %li
        %h3= link_to project.name, project_path(project)
        %p= truncate(project.try(:description))
      