config/routes.rb
Ideagora::Application.routes.draw do

  get "welcome/index"
  get "sign_in" => "sessions#new", :as => "sign_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "my_profile" => "users#edit", :as => "my_profile"
  get "projects" => "projects#index", :as => "projects"
  
  resources :camps
  resources :notices
  resources :sessions
  resources :talks
  resources :venues
  resources :users, :only => [:index, :show, :edit, :update] do
    resources :projects
  end

  root :to => "welcome#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates_presence_of :name, :owner
  
  belongs_to :owner, :class_name => "User", :foreign_key => :user_id
end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base
  before_filter :requires_login, :except => [:index, :show]
  before_filter :requires_owner, :except => [:index, :show, :new, :create]
  
  
  def create
    @project = Project.new(params[:project])
    @project.owner = current_user
    create! { user_path(current_user) }
  end
  
  def update
    update! { user_path(current_user) }
  end
  
private
  def requires_owner
    unless is_owner?
      redirect_to :back
      flash[:alert] = 'You cannot edit projects that are not yours'
    end
  end
  
  def is_owner?
    resource.owner == current_user
  end
  helper_method :is_owner?
  
  def collection
    @projects ||= if current_user
                    current_user.projects
                  else
                    Project.all
                  end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
- simple_form_for([current_user, @project]) do |f|
  = f.input :name
  = f.input :description, :hint => 'Textile supported'
  = f.input :help, :label => 'Need help?'
  
  = f.button :submit

app/views/projects/_project.html.haml
%li[project]
  %h3= link_to project.name, user_project_path(project.owner, project)
  - if current_user and project.owner != current_user
    %p
      by
      = link_to project.owner.full_name, user_path(project.owner)
  %p= truncate(project.try(:description))
  - if project.help
    %p.help Could use help with this one
  - if project.owner == current_user
    %p
      = link_to 'Edit', edit_user_project_path(project.owner, project)
      = link_to 'Delete', user_project_path(project.owner, project), :confirm => 'Are you sure you want to delete this project?', :method => :delete

app/views/projects/_projects.html.haml
%ul
  - @projects.each do |project|
    = render project

app/views/projects/edit.html.haml
%h2 Edit project

= render 'form'

app/views/projects/index.html.haml
%h1 All projects

= render 'projects'

app/views/projects/new.html.haml
%h2 Create a new project

= render 'form'

app/views/projects/show.html.haml
%h1= @project.name

%h3= link_to @project.owner.full_name, user_path(@project.owner)

-if @project.description
  = textilize(@project.description)